<a href="https://colab.research.google.com/github/fabiobasson/python_dataanalysis_book/blob/main/python_dataanalysis_chapter02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd;

In [4]:
names_1880 = pd.read_csv('yob1880.txt',names=['Nomes','Sexo','Aniversario'])

In [5]:
names_1880.head ()

Nomes Sexo  Aniversario
0       Mary    F         7065
1       Anna    F         2604
2       Emma    F         2003
3  Elizabeth    F         1939
4     Minnie    F         1746

In [6]:
names_1880

Nomes Sexo  Aniversario
0          Mary    F         7065
1          Anna    F         2604
2          Emma    F         2003
3     Elizabeth    F         1939
4        Minnie    F         1746
...         ...  ...          ...
1995     Woodie    M            5
1996     Worthy    M            5
1997     Wright    M            5
1998       York    M            5
1999  Zachariah    M            5

[2000 rows x 3 columns]

In [7]:
names_1880.groupby('Sexo').Aniversario.sum()

Sexo
F     90994
M    110490
Name: Aniversario, dtype: int64

In [8]:
years=range(1902,2011)
pieces=[]
columns = ['Nome', 'Sexo', 'Aniversario']


In [9]:
for year in years:
  path='names/yob%d.txt'  % year
  frame = pd.read_csv(path,names=columns)

  frame['year'] = year
  pieces.append(frame)

  names = pd.concat(pieces,ignore_index=True)


FileNotFoundError: ignored

In [10]:
names


NameError: ignored

In [11]:
def add_prop(group):
  Aniversario = group.Aniversario.astype(float)
  group['prop']=Aniversario/Aniversario.sum()
  return group



In [12]:
names = names.groupby(['year', 'Sexo']).apply(add_prop)

NameError: ignored

In [ ]:
names

In [ ]:
def get_top1000(group):
  return group.sort_index(level='Aniversario',ascending=False)[:3]



In [ ]:
grouped = names.groupby(['year', 'Sexo'])


In [ ]:
top1000 = grouped.apply(get_top1000)

In [ ]:
top1000

In [ ]:
# Chapter 3 - Page 46

In [ ]:
top1000

In [28]:
from numpy.random import randn
data = {i : randn() for i in range(7)}
print (data)


{0: -0.6782921311093129, 1: 0.7285641506671403, 2: 2.005198766566372, 3: 0.20881184569522726, 4: -1.0596746676677165, 5: -0.7492819360814431, 6: 0.5584484580543553}


In [59]:
tupla = (1,2,3)

In [60]:
tupla

(1, 2, 3)

In [82]:
tupla2 =([1,4,5],[8,9])


In [84]:
tupla2[1]

[8, 9]

In [86]:
tupla2[1].append(10)

In [87]:
tupla2

([1, 4, 5], [8, 9, 5, 10])

In [101]:
import numpy as np;


In [96]:
data1 = [6, 7.5, 8, 0, 1]


In [97]:
data1

[6, 7.5, 8, 0, 1]

In [100]:
arr1 = np.array(data1)


In [102]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [103]:
arr1.dtype

dtype('float64')

In [104]:
arr1.shape

(5,)

In [113]:
data2=[1,2,3,4],[5,6,.4,8]

In [114]:
data2

([1, 2, 3, 4], [5, 6, 0.4, 8])

In [115]:
arr2=np.array(data2)

In [116]:
arr2;arr2.shape

(2, 4)

In [117]:
arr2.ndim

2

In [118]:
arr2.dtype

dtype('float64')

In [120]:
arr3 = np.zeros(10)

In [121]:
arr3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [122]:
arr3.dtype

dtype('float64')

In [123]:
arr3.shape

(10,)

In [124]:
 np.empty((2, 3, 2))


array([[[6.94868819e-310, 6.94868819e-310],
        [6.94868819e-310, 6.94868819e-310],
        [6.94868819e-310, 6.94868819e-310]],

       [[6.94868819e-310, 6.94868819e-310],
        [6.94868819e-310, 6.94868819e-310],
        [6.94868819e-310, 6.94868819e-310]]])

In [127]:
lista1 = ['ola','vasco']

In [129]:
lista1.append('fla')

In [130]:
lista1

['ola', 'vasco', 'fla']

In [132]:
lista1.remove('fla')

In [133]:
lista1

['ola', 'vasco']

In [135]:
lista1.sort()

In [136]:
seq = [7, 2, 3, 7, 5, 6, 0, 1]

In [137]:
seq[0:2]

[7, 2]

In [140]:
seq[:4]

[7, 2, 3, 7]

In [141]:
seq[2:]

[3, 7, 5, 6, 0, 1]

In [142]:
seq[-1]

1

In [144]:
seq[::1]

[7, 2, 3, 7, 5, 6, 0, 1]

In [145]:
np.arange(15)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [153]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)


In [154]:
numeric_strings.dtype

dtype('S4')

In [155]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [156]:
numeric_strings.dtype

dtype('S4')

In [ ]:
page 84